import {
  Search,
  Bell,
  ChartColumn,
  FileText,
  LayoutGrid,
  Settings,
  Info,
  Moon,
  Sun,
  SlidersHorizontal,
  Trash2,
  CirclePlus ,
  BadgeDollarSign,
  Newspaper,
  LineChart,
  House,
  ArrowRight,
  RefreshCw,
  Gift,
  Gem,
  Split,
  CalendarDays,
  Presentation,
  Building2,
  BadgeIndianRupee,
  Wallet,
  Coins,
  TrendingUp,
  Percent,
  CircleDollarSign,
  BookOpen,
  Banknote,
  Scale,
  ShieldCheck,
} from "lucide-react";

export const Icons = {
  SearchIcon: Search,
  BellIcon: Bell,
  ChartColumnIcon: ChartColumn,
  FileTextIcon: FileText,
  LayoutGridIcon: LayoutGrid,
  SettingsIcon: Settings,
  InfoIcon: Info,
  MoonIcon: Moon,
  SunIcon: Sun,
  SlidersHorizontalIcon: SlidersHorizontal,
  DeleteIcon: Trash2,
  CirclePlusIcon: CirclePlus,
  BadgeDollarSignIcon: BadgeDollarSign,
  NewspaperIcon: Newspaper,
  LineChartIcon: LineChart,
  HouseIcon: House,
  ArrowRightIcon: ArrowRight,
  DividendIcon: Gift,
  BuybackIcon: RefreshCw,
  BonusIcon: Gem,
  SplitIcon: Split,
  CalendarDaysIcon: CalendarDays,
  PresentationIcon: Presentation,
  Building2Icon: Building2,
  BadgeIndianRupeeIcon: BadgeIndianRupee,
  WalletIcon: Wallet,
  CoinsIcon: Coins,
  TrendingUpIcon: TrendingUp,
  PercentIcon: Percent,
  CircleDollarSignIcon: CircleDollarSign,
  BookOpenIcon: BookOpen,
  BanknoteIcon: Banknote,
  ScaleIcon: Scale,
  ShieldCheckIcon: ShieldCheck,
}